moa_dict = {
    "paclitaxel":      "microtubule disrupting",
    "epothilone-B":    "microtubule disrupting",
    "colchicine":      "microtubule disrupting",
    "nocodazole":      "microtubule disrupting",
    "monastrol":       "microtubule disrupting",
    "ARQ-621":         "microtubule disrupting",
    "barasertib":      "aurora B inhibitor",
    "ZM447439":        "aurora B inhibitor",
    "cytochalasin D":  "actin disrupting",
    "cytochalasin B":  "actin disrupting",
    "jaksplakinolide": "actin disrupting",
    "lantrunculin-B":  "actin disrupting",
    "MG132":           "protein degradation",
    "lactacystin":     "protein degradation",
    "ALLN":            "protein degradation",
    "ALLM":            "protein degradation",
    "emetine":         "protein synthesis",
    "cycloheximide":   "protein synthesis",
    "dasatinib":       "kinase inhibitor",
    "saracatinib":     "kinase inhibitor",
    "lovastatin":      "statin",
    "simvastatin":     "statin",
    "camptothecin":    "DNA damaging agent",
    "sn38":            "DNA damaging agent",
    "DMSO":            "control",
    "STS":             "control"
}
